#!/bin/bash
#remaster lib
[ -d "<LIBDIR>" ] || { echo "LIBDIR not exist"; exit 1; }

#check_config [log_file]
function check_config() {

    #LOG
    {
      log_file=$1
      [ -z "$log_file" ] && log_file="/tmp/remaster_`date '+%Y-%m-%d'`"

      if [ -f "$log_file" ]; then
        echo > "$log_file"
      else
        #check if folder exist
        [ -d "${log_file%/*}" ] || {
            # N-> exit 3
            echo "Directory for Log didnt exist"
            exit 3
        }
        #create LOG
        touch "$log_file"
      fi
    }



    #Project
    [ -f "<LIBDIR>/proj/$distro" ] || {
        echo "No Project \"$distrp\" is not supported" | tee -a "$log_file"
        return 3
    }

    #check live-system files
    if [ -f "$iso_source" ]; then
        if [ -n "$iso_destination" ] && [ -d "${iso_destination%/*}" ]; then
            # iso_source -> iso_destination
            # iso_source -> squashfs [optinal]
        else
            if [ -n "$filesystem_source" ] && [ -d "${filesystem_source%/*}" ]; then
                # iso_source -> squashfs
            else
                # ERROR
                echo "No corect AIM in Settings" | tee -a "$log_file"
                return 3
            fi
        fi
    else
        if [ -f "$filesystem_source" ]; then
            if [ -n "$iso_destination" ]; then
                # ERROR
                echo "only Squashfs source in Settings, cant creat ISO" | tee -a "$log_file"
                return 3
            else
                # squashfs -> squashfs
            fi
        else
            # ERROR
            echo "No corect Source in Settings" | tee -a "$log_file"
            return 3
        fi
    fi


}

#this func is standalone executable
[ -n "$1" ] && {
    check_config $@
}
