#!/bin/bash
#remaster lib
[ -d "<LIBDIR>"] || { echo "LIBDIR not exist"; exit 1; }

#chroot_clean [chroot_dir]
function chroot_clean() {
	echo "clean chroot ... "

	chroot_dir="$1"

	chroot "$chroot_dir" /bin/bash -c "apt-get clean"
	chroot "$chroot_dir" /bin/bash -c "rm -r /var/cache/apt/*"
	chroot "$chroot_dir" /bin/bash -c "apt-get update"
	chroot "$chroot_dir" /bin/bash -c "apt-get check"

	echo "done"
}
