#!/bin/bash
#remaster lib
[ -d "<LIBDIR>" ] || { echo "LIBDIR not exist"; exit 1; }

#workspace_erase [workspace_path]
function workspace_erase() {
	echo -n "erase workspace ... "

	for dir in "$@"; do
		[ -d "$dir" ] && rm -r -f "$dir"
	done

	echo "done"
}

#this func is standalone executable
[ -n "$1" ] && {
  workspace_erase $@
}
