#!/bin/bash
#remaster lib
[ -d "<LIBDIR>" ] || { echo "LIBDIR not exist"; exit 1; }

#workspace_erase [workspace_path]
function workspace_erase() {
	echo -n "erase workspace ... "

	for dir in "$@"; do
		[ -d "$dir" ] && rm -r -f "$dir"
	done

	#lxc
	[ -d /var/lib/lxc/_remaster_/ ] && rm -R /var/lib/lxc/_remaster_/

	echo "done"
}

[ -n "$1" ] && {
  echo param
  $1
}
