#!/bin/bash
#remaster lib
[ -d "<LIBDIR>" ] || { echo "LIBDIR not exist"; exit 1; }

##################
##### B a s e ####
##################
# .

# Enviroment
project_relation=""
[ -z "$project" ] && project=base
config_keys="iso_source iso_aim iso_lable squashfs_path proxy_host proxy_port domain nameserver project log_file log_mail_source log_mail_smtp log_mail_aim log_mail_subject tools_list"


#tools_add [chroot_dir] [tools_list]
function tools_add() {
	echo "$project: tools_add ot available"
}

#os_update [chroot_dir]
function os_update() {
	echo "$project: os_update ot available"
}

#proxy_enable [chroot_dir] [proxy_host] [proxy_port]
function proxy_enable() {
	echo "$project: proxy_enable ot available"
}

#dns_set [chroot_dir] [domain] [nameserver]
function dns_set() {
	echo "$project: dns_set ot available"
}

function project_mods() {
	echo "$project: project_mods ot available"
}
