#!/bin/bash
#remaster lib
[ -d "<LIBDIR>" ] || { echo "LIBDIR not exist"; exit 1; }

####################################
##### Base Template U B U N T U ####
####################################
# . -> debian
source <LIBDIR>/proj/debian

[ -n "$1" ] && {
  echo param
  $1
}
